[project]
name = "ht-vasp"
version = "0.1.0"
description = "High-throughput VASP workflows for Multi-Principal Element Alloys"
authors = [{ name = "Barabama", email = "barabama@qq.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Materials Science",
]
dependencies = [
    "atomate2==0.0.22",
    "pymatgen==2025.6.14",
    "phonopy==2.42.0",
    "mp-api==0.45.15",
    "more_itertools==10.8.0",
    "lxml==5.4.0",
    "seekpath==2.1.0",
]

[project.optional-dependencies]
dev = ["pytest>=6.0", "black"]

[project.urls]
Homepage = "https://gitee.com/wubo-movers/ht-vasp"
Repository = "https://gitee.com/wubo-movers/ht-vasp.git"

[build-system]
requires = ["setuptools>=60", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["htvasp*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
